spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ssafy
  jpa:
    open-in-view: false
    hibernate:
#      dialect: org.hibernate.spatial.dialect.mysql.MySQL56InnoDBSpatialDialect
#      database-platform: org.hibernate.spatial.dialect.mysql.MySQL56InnoDBSpatialDialect
      ddl-auto: update
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  rabbitmq:
    port: 5672
    username: ssafy
  redis:
    port: 6379
    username: ssafy
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://www.googleapis.com/service_accounts/v1/jwk/securetoken%40system.gserviceaccount.com

com:
  cotyledon:
    appletree:
      firebase-project-id: apple-story
      firebase-service-account-secret: classpath:firebase-service-account-production-secret.json
      rabbitmq:
        stomp-port: 61613
