spring:
  datasource:
    url: jdbc:mysql://localhost:3306/apple_tree?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true
    password: ssafy
  output:
    ansi:
      enabled: always
  rabbitmq:
    host: localhost
    password: ssafy
  redis:
    host: localhost
    password: adpass

logging:
  level:
    com.cotyledon.appletree: debug
    org.springframework.web: debug
