spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  output:
    ansi:
      enabled: always
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://www.googleapis.com/service_accounts/v1/jwk/securetoken%40system.gserviceaccount.com
  jpa:
    open-in-view: false
    hibernate:
#      dialect: org.hibernate.spatial.dialect.mysql.MySQL56InnoDBSpatialDialect
      database-platform: org.hibernate.spatial.dialect.mysql.MySQL56InnoDBSpatialDialect
      format_sql: true
      ddl-auto: update
      show-sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

com:
  cotyledon.appletree:
      firebase_project_id: apple-tree-7f863